import { Height } from "@mui/icons-material";
import { Box, Paper } from "@mui/material";
import Head from "next/head";
import Header from "../components/header/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <Header />
      </Box>
    </>
  );
}
